services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - taskflow-frontend
      - taskflow-backend
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: dockerfile
    container_name: taskflow-api
    env_file:
      - ./api/.env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - taskflow-backend
      - taskflow-frontend
    command: [ "./server", "-d", "postgres" ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=(Host(`localhost`) || Host(`frontend.localhost`)) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.priority=100"
      - "traefik.http.services.api.loadbalancer.server.port=8080"

  web:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: taskflow-web
    env_file:
      - ./frontend/.env
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - taskflow-frontend
    command: [ "nginx", "-g", "daemon off;" ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`) || Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  postgres:
    image: postgres:latest
    container_name: taskflow-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - taskflow-backend

volumes:
  pgdata:


networks:
  taskflow-backend:
    driver: bridge
  taskflow-frontend:
    driver: bridge
